# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-04-20 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenterlight', '0027_dclcalculatorpluginmodel_enable_512mb_ram'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeplan',
            name='stripe_plan_name',
            field=models.CharField(default='', max_length=512, null=True),
        ),
    ]
