# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-04-20 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenterlight', '0028_stripeplan_stripe_plan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeplan',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stripeplan',
            name='interval',
            field=models.CharField(default='', max_length=128, null=True),
        ),
    ]
