# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-12-24 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenterlight', '0029_auto_20190420_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='dclnavbarpluginmodel',
            name='show_non_transparent_navbar_always',
            field=models.BooleanField(default=False, help_text='Check this if you want to show non transparent navbar only.(Useful when we want to setup a simple page)'),
        ),
    ]
