# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2020-02-04 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenterlight', '0030_dclnavbarpluginmodel_show_non_transparent_navbar_always'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmpricing',
            name='stripe_coupon_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
