# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-04-03 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0050_monthlyhostingbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyhostingbill',
            name='subscription_ids_csv',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='monthlyhostingbill',
            name='lines_meta_data_csv',
            field=models.TextField(default=''),
        ),
    ]
