# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-04-13 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0051_auto_20190403_0703'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingBillLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('discountable', models.BooleanField()),
                ('metadata', models.CharField(max_length=128)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('proration', models.BooleanField()),
                ('quantity', models.PositiveIntegerField()),
                ('unit_amount', models.PositiveIntegerField()),
                ('monthly_hosting_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosting.MonthlyHostingBill')),
            ],
            options={
                'permissions': (('view_hostingbilllineitem', 'View Monthly Hosting Bill Line Item'),),
            },
            bases=(utils.mixins.AssignPermissionsMixin, models.Model),
        ),
    ]
