# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-04-20 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacenterlight', '0028_stripeplan_stripe_plan_name'),
        ('hosting', '0052_hostingbilllineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingbilllineitem',
            name='stripe_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datacenterlight.StripePlan'),
        ),
    ]
