# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-05-08 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0053_hostingbilllineitem_stripe_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmdetail',
            name='configuration',
            field=models.CharField(default='', max_length=128),
        ),
    ]
