# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-07-01 16:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0054_auto_20190508_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhostingkey',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
