# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-10-26 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0055_auto_20190701_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostingbilllineitem',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
