# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-11-15 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import utils.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0056_auto_20191026_0454'),
    ]

    operations = [
        migrations.CreateModel(
            name='VATRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('stop_date', models.DateField(blank=True, null=True)),
                ('territory_codes', models.TextField(blank=True, default='')),
                ('currency_code', models.CharField(max_length=10)),
                ('rate', models.FloatField()),
                ('rate_type', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
            ],
            bases=(utils.mixins.AssignPermissionsMixin, models.Model),
        ),
    ]
