# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-11-15 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0057_vatrates'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericproduct',
            name='product_subscription_interval',
            field=models.CharField(default='month', help_text='Choose between `year` and `month`', max_length=10),
        ),
    ]
