# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2020-01-05 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import utils.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0058_genericproduct_product_subscription_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeTaxRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate_id', models.CharField(max_length=100, unique=True)),
                ('jurisdiction', models.CharField(max_length=10)),
                ('inclusive', models.BooleanField(default=False)),
                ('display_name', models.CharField(max_length=100)),
                ('percentage', models.FloatField(default=0)),
                ('description', models.CharField(max_length=100)),
            ],
            bases=(utils.mixins.AssignPermissionsMixin, models.Model),
        ),
    ]
