# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2020-06-30 19:12

from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0059_stripetaxrate'),
    ]

    operations = [
        migrations.RunSQL(
            "update hosting_vatrates set stop_date = '2020-06-30' where territory_codes = 'DE' and rate = '0.19'",
            "insert into hosting_vatrates (start_date, stop_date, territory_codes, currency_code, rate, rate_type, description) values ('2020-07-01',null,'DE', 'EUR', '0.16', 'standard', 'Germany (member state) standard VAT rate - COVID 19 reduced rate')",
            "update hosting_stripetaxrate set description = 'VAT for DE pre-COVID-19' where description = 'VAT for DE'"

        )
    ]
