# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2020-07-21 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0060_update_DE_vat_covid-19'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericproduct',
            name='exclude_vat_calculations',
            field=models.BooleanField(default=False, help_text='When checked VAT calculations are excluded for this product'),
        ),
    ]
