# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2020-12-23 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import utils.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0061_genericproduct_exclude_vat_calculations'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncompleteSubscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField()),
                ('subscription_id', models.CharField(max_length=100)),
                ('subscription_status', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('request', models.TextField()),
                ('stripe_api_cus_id', models.CharField(max_length=30)),
                ('card_details_response', models.TextField()),
                ('stripe_subscription_obj', models.TextField()),
                ('stripe_onetime_charge', models.TextField()),
                ('gp_details', models.TextField()),
                ('specs', models.TextField()),
                ('vm_template_id', models.PositiveIntegerField(default=0)),
                ('template', models.TextField()),
                ('billing_address_data', models.TextField()),
            ],
            bases=(utils.mixins.AssignPermissionsMixin, models.Model),
        ),
    ]
