# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2020-12-23 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0062_incompletesubscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incompletesubscriptions',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
