# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2020-12-31 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import utils.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0063_auto_20201223_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncompletePaymentIntents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_intent_id', models.CharField(max_length=100)),
                ('request', models.TextField()),
                ('stripe_api_cus_id', models.CharField(max_length=30)),
                ('card_details_response', models.TextField()),
                ('stripe_subscription_id', models.TextField()),
                ('stripe_charge_id', models.TextField()),
                ('gp_details', models.TextField()),
                ('billing_address_data', models.TextField()),
            ],
            bases=(utils.mixins.AssignPermissionsMixin, models.Model),
        ),
    ]
