# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2020-12-31 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0064_incompletepaymentintents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incompletepaymentintents',
            name='stripe_charge_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incompletepaymentintents',
            name='stripe_subscription_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
