# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2023-07-27 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0065_auto_20201231_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericproduct',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='genericproduct',
            name='product_vat',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
