# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-11-28 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_deleteduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='import_stripe_bill_remark',
            field=models.TextField(default='', help_text='Indicates any issues while importing stripe bills'),
        ),
    ]
