# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-12-18 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import membership.models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0010_customuser_import_stripe_bill_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='in_ldap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=50, validators=[membership.models.validate_name]),
        ),
    ]
