# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-12-17 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0010_customuser_import_stripe_bill_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='vat_number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
