# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-12-10 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0010_customuser_import_stripe_bill_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
