# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-12-10 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0012_auto_20191210_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='in_ldap',
            field=models.BooleanField(default=False),
        ),
    ]
