# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-12-10 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0013_customuser_in_ldap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='in_ldap',
        ),
    ]
