# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-12-13 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0015_customuser_in_ldap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
    ]
