# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-12-09 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ungleich_page', '0020_auto_20180320_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='ungleichproduct',
            name='animate',
            field=models.BooleanField(default=True),
        ),
    ]
