apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: {name: {{ .Release.Name }}}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- with .Values.ingress.tlsSecret }}
  tls: [{secretName: {{ . }}, hosts: {{ $.Values.ingress.hosts | toJson }}}]
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - {path: /, pathType: Prefix, backend: {service: {name: {{ $.Release.Name }}-web, port: {number: 80}}}}
    {{- end }}
