# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-12-26 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_auto_20191226_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='vat_validation_status',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='userbillingaddress',
            name='vat_validation_status',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
