# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-12-25 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_auto_20191225_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='vat_number_validated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbillingaddress',
            name='vat_number_validated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
