# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-12-25 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0008_auto_20191225_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='stripe_tax_id',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbillingaddress',
            name='stripe_tax_id',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
